name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 0"  # every Sunday at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compatibility-check:
    name: Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          cache: false

      - name: Create tables
        run: pixi run create-tables

      - name: Check tables
        run: pixi run check-tables

      - name: Assert success ratio
        run: pixi run check-success-ratio
